package client

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"conner/internal/tor"
)

type P2PService struct {
	OnionAddr string
	Port      int
	Token     string // Hash of the RoomKey
	files     map[string]string // FileID -> LocalPath
	order     []string          // Keep track of insertion order
	mu        sync.RWMutex
	server    *http.Server
	tor       *tor.EmbeddedTor
}

func StartP2PService(et *tor.EmbeddedTor) (*P2PService, error) {
	s := &P2PService{
		files: make(map[string]string),
		order: make([]string, 0),
		tor:   et,
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/p2p_download", s.handleDownload)

	listener, err := net.Listen("tcp", "127.0.0.1:8888")
	if err != nil {
		// Fallback to random port if 8888 is busy
		listener, err = net.Listen("tcp", "127.0.0.1:0")
		if err != nil { return nil, err }
	}
	s.Port = listener.Addr().(*net.TCPAddr).Port

	s.server = &http.Server{Handler: mux}
	go s.server.Serve(listener)

	if et != nil {
		go func() {
			// Map onion port 80 to local P2P listener port
			addr, err := et.CreateServerOnion(context.Background(), 80, s.Port)
			if err == nil {
				s.mu.Lock()
				s.OnionAddr = addr
				s.mu.Unlock()
			}
		}()
	} else {
		// System Tor fallback: Read hostname generated by system Tor process
		go func() {
			// Path matches HiddenServiceDir in config.GetTorrcTemplate
			hostnamePath := filepath.Join(".conner_data", "tor", "conner_client", "hostname")
			for i := 0; i < 30; i++ {
				if b, err := os.ReadFile(hostnamePath); err == nil {
					s.mu.Lock()
					s.OnionAddr = strings.TrimSpace(string(b))
					s.mu.Unlock()
					return
				}
				time.Sleep(1 * time.Second)
			}
		}()
	}

	return s, nil
}

func (s *P2PService) handleDownload(w http.ResponseWriter, r *http.Request) {
	fileID := r.URL.Query().Get("id")
	auth := r.Header.Get("Authorization")
	clientHash := strings.TrimPrefix(auth, "Bearer ")

	s.mu.RLock()
	localPath, exists := s.files[fileID]
	myToken := s.Token
	s.mu.RUnlock()

	if !exists {
		http.Error(w, "File not found", http.StatusNotFound)
		return
	}

	if clientHash == "" || clientHash != myToken {
		http.Error(w, "Unauthorized: Key mismatch", http.StatusUnauthorized)
		return
	}

	f, err := os.Open(localPath)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer f.Close()

	w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%s", filepath.Base(localPath)))
	io.Copy(w, f)
}

func (s *P2PService) AddFile(fileID, path string) {
	s.mu.Lock()
	defer s.mu.Unlock()

	// Add to map and tracking slice
	s.files[fileID] = path
	s.order = append(s.order, fileID)

	// Prune if too many files (keep last 20)
	if len(s.order) > 20 {
		oldID := s.order[0]
		s.order = s.order[1:]
		
		oldPath, exists := s.files[oldID]
		if exists {
			delete(s.files, oldID)
			// If it's a temporary zip in temp_shares, delete it from disk
			if filepath.Base(filepath.Dir(oldPath)) == "temp_shares" {
				os.Remove(oldPath)
			}
		}
	}
}

func (s *P2PService) GetOnionAddr() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.OnionAddr
}

func (s *P2PService) UpdateToken(roomKey []byte) {
	if len(roomKey) == 0 { return }
	h := sha256.New()
	h.Write(roomKey)
	s.mu.Lock()
	s.Token = hex.EncodeToString(h.Sum(nil))
	s.mu.Unlock()
}
