// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: internal/protocol/conner.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X25519Pub     []byte                 `protobuf:"bytes,1,opt,name=x25519_pub,json=x25519Pub,proto3" json:"x25519_pub,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PowDifficulty uint32                 `protobuf:"varint,3,opt,name=pow_difficulty,json=powDifficulty,proto3" json:"pow_difficulty,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyExchange) Reset() {
	*x = KeyExchange{}
	mi := &file_internal_protocol_conner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchange) ProtoMessage() {}

func (x *KeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_conner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchange.ProtoReflect.Descriptor instead.
func (*KeyExchange) Descriptor() ([]byte, []int) {
	return file_internal_protocol_conner_proto_rawDescGZIP(), []int{0}
}

func (x *KeyExchange) GetX25519Pub() []byte {
	if x != nil {
		return x.X25519Pub
	}
	return nil
}

func (x *KeyExchange) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *KeyExchange) GetPowDifficulty() uint32 {
	if x != nil {
		return x.PowDifficulty
	}
	return 0
}

func (x *KeyExchange) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X25519Pub     []byte                 `protobuf:"bytes,1,opt,name=x25519_pub,json=x25519Pub,proto3" json:"x25519_pub,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Identity      string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	SigningPub    []byte                 `protobuf:"bytes,4,opt,name=signing_pub,json=signingPub,proto3" json:"signing_pub,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	PowNonce      uint64                 `protobuf:"varint,6,opt,name=pow_nonce,json=powNonce,proto3" json:"pow_nonce,omitempty"`
	E2EPub        []byte                 `protobuf:"bytes,7,opt,name=e2e_pub,json=e2ePub,proto3" json:"e2e_pub,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_internal_protocol_conner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_conner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_internal_protocol_conner_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetX25519Pub() []byte {
	if x != nil {
		return x.X25519Pub
	}
	return nil
}

func (x *ClientHello) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ClientHello) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ClientHello) GetSigningPub() []byte {
	if x != nil {
		return x.SigningPub
	}
	return nil
}

func (x *ClientHello) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ClientHello) GetPowNonce() uint64 {
	if x != nil {
		return x.PowNonce
	}
	return 0
}

func (x *ClientHello) GetE2EPub() []byte {
	if x != nil {
		return x.E2EPub
	}
	return nil
}

func (x *ClientHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HandshakeOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultPort     int32                  `protobuf:"varint,1,opt,name=vault_port,json=vaultPort,proto3" json:"vault_port,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeOk) Reset() {
	*x = HandshakeOk{}
	mi := &file_internal_protocol_conner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeOk) ProtoMessage() {}

func (x *HandshakeOk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_conner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeOk.ProtoReflect.Descriptor instead.
func (*HandshakeOk) Descriptor() ([]byte, []int) {
	return file_internal_protocol_conner_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeOk) GetVaultPort() int32 {
	if x != nil {
		return x.VaultPort
	}
	return 0
}

func (x *HandshakeOk) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeOk) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type HandshakeErr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeErr) Reset() {
	*x = HandshakeErr{}
	mi := &file_internal_protocol_conner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeErr) ProtoMessage() {}

func (x *HandshakeErr) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_conner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeErr.ProtoReflect.Descriptor instead.
func (*HandshakeErr) Descriptor() ([]byte, []int) {
	return file_internal_protocol_conner_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeErr) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey        string                 `protobuf:"bytes,7,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	IsE2Ee        bool                   `protobuf:"varint,8,opt,name=is_e2ee,json=isE2ee,proto3" json:"is_e2ee,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,9,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Mentions      []string               `protobuf:"bytes,10,rep,name=mentions,proto3" json:"mentions,omitempty"`
	FileId        string                 `protobuf:"bytes,11,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIdx      int32                  `protobuf:"varint,12,opt,name=chunk_idx,json=chunkIdx,proto3" json:"chunk_idx,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,13,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	OnionAddr     string                 `protobuf:"bytes,14,opt,name=onion_addr,json=onionAddr,proto3" json:"onion_addr,omitempty"`
	RatchetStep   uint32                 `protobuf:"varint,15,opt,name=ratchet_step,json=ratchetStep,proto3" json:"ratchet_step,omitempty"`
	MessageId     string                 `protobuf:"bytes,16,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FileToken     string                 `protobuf:"bytes,17,opt,name=file_token,json=fileToken,proto3" json:"file_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_internal_protocol_conner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_conner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_internal_protocol_conner_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChatMessage) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *ChatMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ChatMessage) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

func (x *ChatMessage) GetIsE2Ee() bool {
	if x != nil {
		return x.IsE2Ee
	}
	return false
}

func (x *ChatMessage) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *ChatMessage) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *ChatMessage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ChatMessage) GetChunkIdx() int32 {
	if x != nil {
		return x.ChunkIdx
	}
	return 0
}

func (x *ChatMessage) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *ChatMessage) GetOnionAddr() string {
	if x != nil {
		return x.OnionAddr
	}
	return ""
}

func (x *ChatMessage) GetRatchetStep() uint32 {
	if x != nil {
		return x.RatchetStep
	}
	return 0
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetFileToken() string {
	if x != nil {
		return x.FileToken
	}
	return ""
}

var File_internal_protocol_conner_proto protoreflect.FileDescriptor

const file_internal_protocol_conner_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/protocol/conner.proto\x12\bprotocol\"\x83\x01\n" +
	"\vKeyExchange\x12\x1d\n" +
	"\n" +
	"x25519_pub\x18\x01 \x01(\fR\tx25519Pub\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12%\n" +
	"\x0epow_difficulty\x18\x03 \x01(\rR\rpowDifficulty\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xf3\x01\n" +
	"\vClientHello\x12\x1d\n" +
	"\n" +
	"x25519_pub\x18\x01 \x01(\fR\tx25519Pub\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\x12\x1f\n" +
	"\vsigning_pub\x18\x04 \x01(\fR\n" +
	"signingPub\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x1b\n" +
	"\tpow_nonce\x18\x06 \x01(\x04R\bpowNonce\x12\x17\n" +
	"\ae2e_pub\x18\a \x01(\fR\x06e2ePub\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\"b\n" +
	"\vHandshakeOk\x12\x1d\n" +
	"\n" +
	"vault_port\x18\x01 \x01(\x05R\tvaultPort\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\"&\n" +
	"\fHandshakeErr\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xec\x03\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x17\n" +
	"\apub_key\x18\a \x01(\tR\x06pubKey\x12\x17\n" +
	"\ais_e2ee\x18\b \x01(\bR\x06isE2ee\x12\x19\n" +
	"\breply_to\x18\t \x01(\tR\areplyTo\x12\x1a\n" +
	"\bmentions\x18\n" +
	" \x03(\tR\bmentions\x12\x17\n" +
	"\afile_id\x18\v \x01(\tR\x06fileId\x12\x1b\n" +
	"\tchunk_idx\x18\f \x01(\x05R\bchunkIdx\x12!\n" +
	"\ftotal_chunks\x18\r \x01(\x05R\vtotalChunks\x12\x1d\n" +
	"\n" +
	"onion_addr\x18\x0e \x01(\tR\tonionAddr\x12!\n" +
	"\fratchet_step\x18\x0f \x01(\rR\vratchetStep\x12\x1d\n" +
	"\n" +
	"message_id\x18\x10 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"file_token\x18\x11 \x01(\tR\tfileTokenB\x1aZ\x18conner/internal/protocolb\x06proto3"

var (
	file_internal_protocol_conner_proto_rawDescOnce sync.Once
	file_internal_protocol_conner_proto_rawDescData []byte
)

func file_internal_protocol_conner_proto_rawDescGZIP() []byte {
	file_internal_protocol_conner_proto_rawDescOnce.Do(func() {
		file_internal_protocol_conner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_conner_proto_rawDesc), len(file_internal_protocol_conner_proto_rawDesc)))
	})
	return file_internal_protocol_conner_proto_rawDescData
}

var file_internal_protocol_conner_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_protocol_conner_proto_goTypes = []any{
	(*KeyExchange)(nil),  // 0: protocol.KeyExchange
	(*ClientHello)(nil),  // 1: protocol.ClientHello
	(*HandshakeOk)(nil),  // 2: protocol.HandshakeOk
	(*HandshakeErr)(nil), // 3: protocol.HandshakeErr
	(*ChatMessage)(nil),  // 4: protocol.ChatMessage
}
var file_internal_protocol_conner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_conner_proto_init() }
func file_internal_protocol_conner_proto_init() {
	if File_internal_protocol_conner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_conner_proto_rawDesc), len(file_internal_protocol_conner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_conner_proto_goTypes,
		DependencyIndexes: file_internal_protocol_conner_proto_depIdxs,
		MessageInfos:      file_internal_protocol_conner_proto_msgTypes,
	}.Build()
	File_internal_protocol_conner_proto = out.File
	file_internal_protocol_conner_proto_goTypes = nil
	file_internal_protocol_conner_proto_depIdxs = nil
}
