// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/protocol/conner.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	PubKey        string                 `protobuf:"bytes,7,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	IsE2Ee        bool                   `protobuf:"varint,8,opt,name=is_e2ee,json=isE2ee,proto3" json:"is_e2ee,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,9,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Mentions      []string               `protobuf:"bytes,10,rep,name=mentions,proto3" json:"mentions,omitempty"`
	FileId        string                 `protobuf:"bytes,11,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIdx      int32                  `protobuf:"varint,12,opt,name=chunk_idx,json=chunkIdx,proto3" json:"chunk_idx,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,13,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	OnionAddr     string                 `protobuf:"bytes,14,opt,name=onion_addr,json=onionAddr,proto3" json:"onion_addr,omitempty"`
	RatchetStep   uint32                 `protobuf:"varint,15,opt,name=ratchet_step,json=ratchetStep,proto3" json:"ratchet_step,omitempty"`
	MessageId     string                 `protobuf:"bytes,16,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FileToken     string                 `protobuf:"bytes,17,opt,name=file_token,json=fileToken,proto3" json:"file_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_internal_protocol_conner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_conner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_internal_protocol_conner_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChatMessage) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *ChatMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ChatMessage) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

func (x *ChatMessage) GetIsE2Ee() bool {
	if x != nil {
		return x.IsE2Ee
	}
	return false
}

func (x *ChatMessage) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *ChatMessage) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *ChatMessage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ChatMessage) GetChunkIdx() int32 {
	if x != nil {
		return x.ChunkIdx
	}
	return 0
}

func (x *ChatMessage) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *ChatMessage) GetOnionAddr() string {
	if x != nil {
		return x.OnionAddr
	}
	return ""
}

func (x *ChatMessage) GetRatchetStep() uint32 {
	if x != nil {
		return x.RatchetStep
	}
	return 0
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetFileToken() string {
	if x != nil {
		return x.FileToken
	}
	return ""
}

var File_internal_protocol_conner_proto protoreflect.FileDescriptor

const file_internal_protocol_conner_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/protocol/conner.proto\x12\bprotocol\"\xec\x03\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x17\n" +
	"\apub_key\x18\a \x01(\tR\x06pubKey\x12\x17\n" +
	"\ais_e2ee\x18\b \x01(\bR\x06isE2ee\x12\x19\n" +
	"\breply_to\x18\t \x01(\tR\areplyTo\x12\x1a\n" +
	"\bmentions\x18\n" +
	" \x03(\tR\bmentions\x12\x17\n" +
	"\afile_id\x18\v \x01(\tR\x06fileId\x12\x1b\n" +
	"\tchunk_idx\x18\f \x01(\x05R\bchunkIdx\x12!\n" +
	"\ftotal_chunks\x18\r \x01(\x05R\vtotalChunks\x12\x1d\n" +
	"\n" +
	"onion_addr\x18\x0e \x01(\tR\tonionAddr\x12!\n" +
	"\fratchet_step\x18\x0f \x01(\rR\vratchetStep\x12\x1d\n" +
	"\n" +
	"message_id\x18\x10 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"file_token\x18\x11 \x01(\tR\tfileTokenB\x1aZ\x18conner/internal/protocolb\x06proto3"

var (
	file_internal_protocol_conner_proto_rawDescOnce sync.Once
	file_internal_protocol_conner_proto_rawDescData []byte
)

func file_internal_protocol_conner_proto_rawDescGZIP() []byte {
	file_internal_protocol_conner_proto_rawDescOnce.Do(func() {
		file_internal_protocol_conner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_conner_proto_rawDesc), len(file_internal_protocol_conner_proto_rawDesc)))
	})
	return file_internal_protocol_conner_proto_rawDescData
}

var file_internal_protocol_conner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protocol_conner_proto_goTypes = []any{
	(*ChatMessage)(nil), // 0: protocol.ChatMessage
}
var file_internal_protocol_conner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_conner_proto_init() }
func file_internal_protocol_conner_proto_init() {
	if File_internal_protocol_conner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_conner_proto_rawDesc), len(file_internal_protocol_conner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_conner_proto_goTypes,
		DependencyIndexes: file_internal_protocol_conner_proto_depIdxs,
		MessageInfos:      file_internal_protocol_conner_proto_msgTypes,
	}.Build()
	File_internal_protocol_conner_proto = out.File
	file_internal_protocol_conner_proto_goTypes = nil
	file_internal_protocol_conner_proto_depIdxs = nil
}
